INGREDIENTES_VALIDOS = [
    "ácido cítrico",
    "ácido fítico",
    "ácido ferúlico",
    "ácido glicólico",
    "ácido hialurônico",
    "ácido kójico",
    "ácido lático",
    "ácido málico",
    "ácido mandélico",
    "ácido salicílico",
    "ácido tranexâmico",
    "água de maçã",
    "alantoína",
    "alfa arbutin",
    "alfa bisabolol",
    "álcool cetílico",
    "álcool terc-butílico",
    "alpha glucan",
    "argila branca",
    "amilopectina",
    "astaxantina",
    "baicalina",
    "benzoato de sódio",
    "bisabolol",
    "butil metoxidibenzoilmetano",
    "butilenoglicol",
    "cafeína",
    " óleo de jojoba",
    "caprililglicol",
    "carnosina",
    "ceramidas",
    "chá verde",
    "citronelol",
    "decil glicosídeo",
    "dimeticona",
    "dipropilenoglicol",
    "esqualano",
    "aloe vera",
    "fenoxietanol",
    "glicerina",
    "gluconolactona",
    "glutationa",
    "goma xantana",
    "hialuronato de sódio",
    "hidróxido de amônio",
    "lecitina",
    "maltodextrina",
    "manteiga de abacate",
    "manteiga de karité",
    "melaleuca",
    "nano retinol",
    "niacinamida",
    "octocrileno",
    "óleo de rosa mosqueta",
    "palmitato de ascorbila",
    "pantenol",
    "pca sódico",
    "peptídeo antiacne",
    "peptídeo antiolheiras",
    "peptídeo antioxidante",
    "peptídeo de cobre",
    "peptídeo uniformizador",
    "peptídeos",
    "peptídeos matrixyl",
    "propanodiol",
    "propilenoglicol",
    "pullulan",
    "quercetina",
    "resveratrol",
    "retinol",
    "silica",
    "sílica",
    "sorbitol",
    "spirulina",
    "taurina",
    "tocopherol",
    "trealose",
    "vitamina b12",
    "vitamina c",
    "vitamina e",
    "xilitol",
    "zinco",
    "esfoliante de bambu",
    "sacarídeo",
]
