INGREDIENTES_VALIDOS = [
    "ácido araquidônico",
    "ácido azeláico",
    "ácido benzóico",
    "ácido cítrico",
    "ácido fítico",
    "ácido ferúlico",
    "ácido glicólico",
    "ácido hialurônico",
    "ácido kójico",
    "ácido lático",
    "ácido linolênico",
    "ácido málico",
    "ácido mandélico",
    "ácido salicílico",
    "ácido sórbico",
    "ácido tranexâmico",
    "água de maçã",
    "alantoína",
    "alfa arbutin",
    "alfa bisabolol",
    "alfa-isometil ionona",
    "álcool cetílico",
    "álcool terc-butílico",
    "alpha glucan",
    "argila branca",
    "amilopectina",
    "astaxantina",
    "baicalina",
    "bacuchiol",
    "benzoato de sódio",
    "bisabolol",
    "butil metoxidibenzoilmetano",
    "butilenoglicol",
    "cafeína",
    " óleo de jojoba",
    "caprililglicol",
    "carnosina",
    "ceramidas",
    "chá verde",
    "citronelol",
    "decil glicosídeo",
    "dimeticona",
    "dipropilenoglicol",
    "esqualano",
    "aloe vera",
    "calêndula",
    "vegetal de cassi alata",
    "fenoxietanol",
    "fosfolípido",
    "glicerina",
    "gluconolactona",
    "glutationa",
    "goma xantana",
    "hialuronato de sódio",
    "hidróxido de amônio",
    "lactato de sódio",
    "lauret sulfossuccinato dissódico",
    "lecitina",
    "maltodextrina",
    "manteiga de abacate",
    "manteiga de karité",
    "manteiga de theobroma cacao",
    "melaleuca",
    "nano retinol",
    "neutrazen™",
    "niacinamida",
    "octocrileno",
    "óleo de amêndoas doces",
    "óleo de rosa mosqueta",
    "palmitato de ascorbila",
    "pantenol",
    "papaína",
    "pca sódico",
    "peptídeo antiacne",
    "peptídeo antiolheiras",
    "peptídeo antioxidante",
    "peptídeo de cobre",
    "peptídeo uniformizador",
    "peptídeos",
    "peptídeos matrixyl",
    "phloretin",
    "phytoesqualano",
    "propanodiol",
    "propilenoglicol",
    "pullulan",
    "quercetina",
    "resveratrol",
    "retinol",
    "silica",
    "silsoft",
    "sílica",
    "sorbitol",
    "spirulina",
    "taurina",
    "tocopherol",
    "trealose",
    "vitamina b12",
    "vitamina c",
    "vitamina e",
    "xilitol",
    "zinco",
    "esfoliante de bambu",
    "sacarídeo"
]
