INGREDIENTES_VALIDOS = [
    "ácido hialurônico",
    "esqualano",
    "extrato de calêndula",
    "extrato vegetal de cassi alata",
    "manteiga de karité",
    "niacinamida",
    "óleo de amêndoas doces",
    "óleo de rosa mosqueta",
    "vitamina c",
    "vitamina e",
    "ácido tranexâmico",
    "ácido glicólico",
    "ácido salicílico",
    "retinol",
    "peptídeos",
    "ceramidas",
    "pantenol",
    "aloe vera",
    "ácido kójico",
    "ácido azeláico",
    "ácido fítico",
    "ácido lático",
    "ácido maltobiônico",
    "ácido mandélico",
    "alfa arbutin",
    "alfa bisabolol",
    "astaxantina",
    "baicalina",
    "carnosina",
    "chá verde",
    "enzima papaína",
    "flor de lótus",
    "melaleuca",
    "peptídeo antiacne",
    "peptídeo antioxidante",
    "peptídeo de cobre",
    "peptídeo uniformizador",
    "peptídeos matrixyl",
    "phytoesqualano",
    "resveratrol",
    "spirulina",
    "zinco pca",
    "nano retinol",
    "cafeína",
    "taurina",
    "peptídeo antiolheiras",
    "glutationa",
    "quercetina",
    "argila branca",
    "alantoína",
    "manteiga de abacate",
    "ácido araquidônico",
    "ácido cítrico",
    "ácido fenilbenzimidazol sulfônico",
    "ácido ferúlico",
    "ácido kójico dipalmitato",
    "ácido linoleico",
    "ácido linolênico",
    "ácido sórbico",
    "álcool cetílico",
    "álcool terc-butílico",
    "amilopectina",
    "ascorbyl glucoside",
    "avocadin™ hu25",
    "azela­midopropyl dimethyl amine",
    "benzoato de sódio",
    "biopeptídeo de cobre",
    "biosaccharide gum 1",
    "bis diglyceryl polyacyladipate 2",
    "bisabolol",
    "butil metoxidibenzoilmetano",
    "butilenoglicol",
    "cafeisilane®",
    "caprililglicol",
    "centella-asiática",
    "cetearyl olivate",
    "creamy multi-peptide complex",
    "cropeptide w",
    "cyclopentasiloxane",
    "decil glicosídeo",
    "dibutyl adipate",
    "dipropilenoglicol",
    "disodium edta",
    "epi-on™",
    "ethoxydiglycol",
    "ethylhexylglycerin",
    "etilhexil triazona",
    "extrato de aloe vera",
    "fenoxietanol",
    "fiberhance bm",
    "filcortex veg",
    "fosfolípido",
    "gluconolactona",
    "goma xantana",
    "hidróxido de amônio",
    "lactato de sódio",
    "lecitina",
    "lha",
    "maltodextrina",
    "matrixyl 3000®",
    "matrixyl® synthe® '6",
    "neutrazen™",
    "octocrileno",
    "palmitato de ascorbila",
    "pca sódico",
    "pentylene glycol",
    "phenoxyethanol",
    "phloretin",
    "polysorbate",
    "prodew 500",
    "propanodiol",
    "propilenoglicol",
    "pullulan",
    "sílica",
    "silsoft",
    "sodium acrylates copolymer",
    "sodium hyaluronate",
    "sodium polyacrylate",
    "stearic acid",
    "tocopherol",
    "vitamina b12",
    "xilitol",
    "zinco",
    "água de maçã",
    "alpha glucan",

    # --- Novos das imagens ---
    "lauret sulfossuccinato dissódico",
    "cocamidopropil betaína",
    "glicerina",
    "peg-7 gliceril cocoato",
    "propilenoglicol",
    "sorbitol",
    "ácido benzóico",
    "citronelol",
    "alfa-isometil ionona",
    "triolato de metilglicol peg-120",
    "ácido salicílico",
    "hidroxietil ureia",
    "extrato de hymenaea courbaril (jatobá)",
    "trealose",
    "ésteres de jojoba",
    "dimeticona",
    "ácido málico",
    "óleo da folha de conobea scoparioides",
    "extrato de folha de schinus terebinthifolius (aroeira)",
    "manteiga de astrocaryum vulgare",
    "manteiga de theobroma cacao",
    "bacuchiol",
    "ácido araquidônico",
    "hialuronato de sódio",
    "ácido araquidônico",
]


# INGREDIENTES_VALIDOS = [
#     "ácido hialurônico",
#     "esqualano",
#     "extrato de calêndula",
#     "extrato vegetal de cassi alata",
#     "manteiga de karité",
#     "niacinamida",
#     "óleo de amêndoas doces",
#     "óleo de rosa mosqueta",
#     "vitamina c",
#     "vitamina e",
#     "ácido tranexâmico",
#     "ácido glicólico",
#     "ácido salicílico",
#     "retinol",
#     "peptídeos",
#     "ceramidas",
#     "pantenol",
#     "aloe vera",
#     "ácido kójico",
#     "ácido azeláico",
#     "ácido fítico",
#     "ácido lático",
#     "ácido maltobiônico",
#     "ácido mandélico",
#     "alfa arbutin",
#     "alfa bisabolol",
#     "astaxantina",
#     "baicalina",
#     "carnosina",
#     "chá verde",
#     "enzima papaína",
#     "flor de lótus",
#     "melaleuca",
#     "peptídeo antiacne",
#     "peptídeo antioxidante",
#     "peptídeo de cobre",
#     "peptídeo uniformizador",
#     "peptídeos matrixyl",
#     "phytoesqualano",
#     "resveratrol",
#     "spirulina",
#     "zinco pca",
#     "nano retinol",
#     "cafeína",
#     "taurina",
#     "peptídeo antiolheiras",
#     "glutationa",
#     "quercetina",
#     "argila branca",
#     "alantoína",
#     "manteiga de abacate",
#     "ácido araquidônico",
#     "ácido cítrico",
#     "ácido fenilbenzimidazol sulfônico",
#     "ácido ferúlico",
#     "ácido kójico dipalmitato",
#     "ácido linoleico",
#     "ácido linolênico",
#     "ácido sórbico",
#     "álcool cetílico",
#     "álcool terc-butílico",
#     "amilopectina",
#     "ascorbyl glucoside",
#     "avocadin™ hu25",
#     "azela­midopropyl dimethyl amine",
#     "benzoato de sódio",
#     "biopeptídeo de cobre",
#     "biosaccharide gum 1",
#     "bis diglyceryl polyacyladipate 2",
#     "bisabolol",
#     "butil metoxidibenzoilmetano",
#     "butilenoglicol",
#     "cafeisilane®",
#     "caprililglicol",
#     "centella-asiática",
#     "cetearyl olivate",
#     "creamy multi-peptide complex",
#     "cropeptide w",
#     "cyclopentasiloxane",
#     "decil glicosídeo",
#     "dibutyl adipate",
#     "dipropilenoglicol",
#     "disodium edta",
#     "epi-on™",
#     "ethoxydiglycol",
#     "ethylhexylglycerin",
#     "etilhexil triazona",
#     "extrato de aloe vera",
#     "fenoxietanol",
#     "fiberhance bm",
#     "filcortex veg",
#     "fosfolípido",
#     "gluconolactona",
#     "goma xantana",
#     "hidróxido de amônio",
#     "lactato de sódio",
#     "lecitina",
#     "lha",
#     "maltodextrina",
#     "matrixyl 3000®",
#     "matrixyl® synthe® '6",
#     "neutrazen™",
#     "octocrileno",
#     "palmitato de ascorbila",
#     "pca sódico",
#     "pentylene glycol",
#     "phenoxyethanol",
#     "phloretin",
#     "polysorbate",
#     "prodew 500",
#     "propanodiol",
#     "propilenoglicol",
#     "pullulan",
#     "sílica",
#     "silsoft",
#     "sodium acrylates copolymer",
#     "sodium hyaluronate",
#     "sodium polyacrylate",
#     "stearic acid",
#     "tocopherol",
#     "vitamina b12",
#     "xilitol",
#     "zinco",
#     "água de maçã",
#     "alpha glucan",
# ]
